services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html/frontend
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core-service
      - math-service

  core-service:
    build:
      context: .
      dockerfile: Dockerfile-service
    command: /app/bin/core-service
    expose:
      - "80"

  math-service:
    build:
      context: .
      dockerfile: Dockerfile-service
    command: /app/bin/math-service
    expose:
      - "80"